version: "3.3"

services:
  start_page:
    container_name: start_page
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=development
